services:
  # Base de données PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: mboa_travel_db
    restart: always
    environment:
      POSTGRES_USER: trevor
      POSTGRES_PASSWORD: TREFRIED1707
      POSTGRES_DB: travelling
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mboa_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trevor -d travelling"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application Flask
  web:
    build: .
    container_name: mboa_travel_app
    restart: "no"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - DATABASE_URL=postgresql://trevor:TREFRIED1707@db:5432/travelling
      - SECRET_KEY=trefried1707_docker_secret_key_2025
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mboa_network
    entrypoint: ["/app/entrypoint.sh"]
    #command: >
  #     sh -c "python -c 'import app; with app.app_context(): app.db.create_all()' && flask run --host=0.0.0.0"
volumes:
  postgres_data:
    driver: local

networks:
  mboa_network:
    driver: bridge