"""Initial migration

Revision ID: 256e622f8f1b
Revises: 
Create Date: 2025-11-21 12:50:37.972145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256e622f8f1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agence',
    sa.Column('id_agence', sa.Integer(), nullable=False),
    sa.Column('nom_agence', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_agence')
    )
    op.create_table('client',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cni', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('paiement',
    sa.Column('id_paiement', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('date_paiement', sa.TIMESTAMP(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('reference_transaction', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_paiement'),
    sa.UniqueConstraint('reference_transaction')
    )
    op.create_table('trajet',
    sa.Column('id_trajet', sa.Integer(), nullable=False),
    sa.Column('ville_depart', sa.String(length=100), nullable=False),
    sa.Column('ville_arrivee', sa.String(length=100), nullable=False),
    sa.Column('tarif_standard', sa.Integer(), nullable=False),
    sa.Column('tarif_vip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_trajet')
    )
    op.create_table('vehicule',
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('capacite', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('immatriculation')
    )
    op.create_table('personnel',
    sa.Column('id_personnel', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id_agence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_agence'], ['agence.id_agence'], ),
    sa.PrimaryKeyConstraint('id_personnel')
    )
    op.create_table('voyage',
    sa.Column('id_voyage', sa.Integer(), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('heure_depart', sa.Time(), nullable=False),
    sa.Column('id_trajet', sa.Integer(), nullable=False),
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('id_agence', sa.Integer(), nullable=True),
    sa.Column('standing', sa.String(length=50), nullable=False),
    sa.Column('places_reservees', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_agence'], ['agence.id_agence'], ),
    sa.ForeignKeyConstraint(['id_trajet'], ['trajet.id_trajet'], ),
    sa.ForeignKeyConstraint(['immatriculation'], ['vehicule.immatriculation'], ),
    sa.PrimaryKeyConstraint('id_voyage')
    )
    op.create_table('expedition',
    sa.Column('num_expedition', sa.String(length=20), nullable=False),
    sa.Column('date_expedition', sa.TIMESTAMP(), nullable=False),
    sa.Column('frais', sa.Integer(), nullable=False),
    sa.Column('nature', sa.String(length=100), nullable=True),
    sa.Column('id_client_expediteur', sa.Integer(), nullable=True),
    sa.Column('id_voyage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client_expediteur'], ['client.id_client'], ),
    sa.ForeignKeyConstraint(['id_voyage'], ['voyage.id_voyage'], ),
    sa.PrimaryKeyConstraint('num_expedition')
    )
    op.create_table('reservation',
    sa.Column('num_reservation', sa.String(length=20), nullable=False),
    sa.Column('date_reservation', sa.TIMESTAMP(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_voyage', sa.Integer(), nullable=False),
    sa.Column('id_paiement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ),
    sa.ForeignKeyConstraint(['id_paiement'], ['paiement.id_paiement'], ),
    sa.ForeignKeyConstraint(['id_voyage'], ['voyage.id_voyage'], ),
    sa.PrimaryKeyConstraint('num_reservation'),
    sa.UniqueConstraint('id_paiement')
    )
    op.create_table('voyage_personnel',
    sa.Column('id_voyage', sa.Integer(), nullable=False),
    sa.Column('id_personnel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_personnel'], ['personnel.id_personnel'], ),
    sa.ForeignKeyConstraint(['id_voyage'], ['voyage.id_voyage'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_voyage', 'id_personnel')
    )
    op.create_table('colis',
    sa.Column('id_colis', sa.Integer(), nullable=False),
    sa.Column('num_expedition', sa.String(length=20), nullable=False),
    sa.Column('nature', sa.String(length=100), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('id_personnel_traiteur', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_personnel_traiteur'], ['personnel.id_personnel'], ),
    sa.ForeignKeyConstraint(['num_expedition'], ['expedition.num_expedition'], ),
    sa.PrimaryKeyConstraint('id_colis')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colis')
    op.drop_table('voyage_personnel')
    op.drop_table('reservation')
    op.drop_table('expedition')
    op.drop_table('voyage')
    op.drop_table('personnel')
    op.drop_table('vehicule')
    op.drop_table('trajet')
    op.drop_table('paiement')
    op.drop_table('client')
    op.drop_table('agence')
    # ### end Alembic commands ###
