"""Ajout des tables nouvelles pour la customisation

Revision ID: a49ccc7c8c6f
Revises: 
Create Date: 2025-12-18 21:21:50.287451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49ccc7c8c6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_touristique',
    sa.Column('id_site', sa.Integer(), nullable=False),
    sa.Column('nom_site', sa.String(length=100), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tarif_adulte', sa.Integer(), nullable=False),
    sa.Column('tarif_enfant', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('coordonnees_gps', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_site')
    )
    op.create_table('excursion',
    sa.Column('id_excursion', sa.Integer(), nullable=False),
    sa.Column('nom_excursion', sa.String(length=200), nullable=False),
    sa.Column('date_depart', sa.Date(), nullable=False),
    sa.Column('date_retour', sa.Date(), nullable=False),
    sa.Column('heure_depart', sa.Time(), nullable=False),
    sa.Column('id_site', sa.Integer(), nullable=False),
    sa.Column('id_agence', sa.Integer(), nullable=True),
    sa.Column('immatriculation', sa.String(length=20), nullable=True),
    sa.Column('nb_places_disponibles', sa.Integer(), nullable=False),
    sa.Column('tarif_par_personne', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_agence'], ['agence.id_agence'], ),
    sa.ForeignKeyConstraint(['id_site'], ['site_touristique.id_site'], ),
    sa.ForeignKeyConstraint(['immatriculation'], ['vehicule.immatriculation'], ),
    sa.PrimaryKeyConstraint('id_excursion')
    )
    op.create_table('location_vehicule',
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('num_location', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=True),
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('tarif_journalier', sa.Integer(), nullable=False),
    sa.Column('caution', sa.Integer(), nullable=False),
    sa.Column('montant_total', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('kilometrage_depart', sa.Integer(), nullable=True),
    sa.Column('kilometrage_retour', sa.Integer(), nullable=True),
    sa.Column('id_paiement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ),
    sa.ForeignKeyConstraint(['id_paiement'], ['paiement.id_paiement'], ),
    sa.ForeignKeyConstraint(['immatriculation'], ['vehicule.immatriculation'], ),
    sa.PrimaryKeyConstraint('id_location'),
    sa.UniqueConstraint('num_location')
    )
    op.create_table('reservation_excursion',
    sa.Column('id_reservation_excursion', sa.Integer(), nullable=False),
    sa.Column('num_reservation', sa.String(length=20), nullable=False),
    sa.Column('date_reservation', sa.TIMESTAMP(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_excursion', sa.Integer(), nullable=False),
    sa.Column('nb_adultes', sa.Integer(), nullable=True),
    sa.Column('nb_enfants', sa.Integer(), nullable=True),
    sa.Column('montant_total', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=True),
    sa.Column('id_paiement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id_client'], ),
    sa.ForeignKeyConstraint(['id_excursion'], ['excursion.id_excursion'], ),
    sa.ForeignKeyConstraint(['id_paiement'], ['paiement.id_paiement'], ),
    sa.PrimaryKeyConstraint('id_reservation_excursion'),
    sa.UniqueConstraint('num_reservation')
    )
    op.create_table('statut_colis',
    sa.Column('id_statut', sa.Integer(), nullable=False),
    sa.Column('num_expedition', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=100), nullable=False),
    sa.Column('date_heure', sa.TIMESTAMP(), nullable=False),
    sa.Column('localisation', sa.String(length=200), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['num_expedition'], ['expedition.num_expedition'], ),
    sa.PrimaryKeyConstraint('id_statut')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statut_colis')
    op.drop_table('reservation_excursion')
    op.drop_table('location_vehicule')
    op.drop_table('excursion')
    op.drop_table('site_touristique')
    # ### end Alembic commands ###
