"""initial schema

Revision ID: c12ccc8c2914
Revises: 
Create Date: 2025-12-11 00:05:29.755497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12ccc8c2914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehicule_immatriculation', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id_client'], ),
    sa.ForeignKeyConstraint(['vehicule_immatriculation'], ['vehicule.immatriculation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tourisme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duree', sa.String(length=50), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('agence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agence_id'], ['agence.id_agence'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tourisme')
    op.drop_table('location')
    # ### end Alembic commands ###
