"""Creation des tables manquantes

Revision ID: e9338c69b710
Revises: c12ccc8c2914
Create Date: 2025-12-14 13:05:38.890518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9338c69b710'
down_revision = 'c12ccc8c2914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehicule_immatriculation', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id_client'], ),
    sa.ForeignKeyConstraint(['vehicule_immatriculation'], ['vehicule.immatriculation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tourisme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duree', sa.String(length=50), nullable=True),
    sa.Column('prix', sa.Float(), nullable=True),
    sa.Column('agence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agence_id'], ['agence.id_agence'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.drop_table('tourisme')
    op.drop_table('location')
    op.drop_table('admin')
    # ### end Alembic commands ###
