"""Migration avec hachage pour Client

Revision ID: f04e8dc1c036
Revises: e9338c69b710
Create Date: 2025-12-17 03:46:44.824691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04e8dc1c036'
down_revision = 'e9338c69b710'
branch_labels = None
depends_on = None

def upgrade():
    # 1. On ajoute la colonne en autorisant le vide (nullable=True)
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))

    # 2. ON REMPLIT LES LIGNES VIDES (Étape manquante)
    # On donne un mot de passe par défaut (ex: 'default_password') à tous les clients existants
    # Note : Dans un vrai projet, il faudrait hacher cette valeur.
    op.execute("UPDATE client SET password_hash = 'default_password_change_me' WHERE password_hash IS NULL")

    # 3. Maintenant qu'il n'y a plus de NULL, on peut mettre la contrainte NOT NULL
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('password_hash', 
                              existing_type=sa.String(length=255), 
                              nullable=False)
        
        # 4. On supprime l'ancienne colonne si elle existe
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        # 1. Rajouter l'ancienne colonne
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        # 2. Supprimer la nouvelle colonne
        batch_op.drop_column('password_hash')
    # ### end Alembic commands ###
